name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.5.2
      with:
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: SSH Setup
      run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme SharkCardScan -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme SharkCardScan -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
